FROM rhcayadav/cygnus_custom-ckan_without_entrypoint:v1.6
MAINTAINER Francisco Romero Bueno <francisco.romerobueno@telefonica.com>


#ENV CYGNUS_SERVICE_PORT "5050"
#ENV CYGNUS_API_PORT "8081"
#ENV CYGNUS_MYSQL_HOST "iot-mysql"
#ENV CYGNUS_MYSQL_PORT "3306"
#ENV CYGNUS_MYSQL_USER "mysql"
#ENV CYGNUS_MYSQL_PASS "mysql"
#ENV CYGNUS_MONGO_HOSTS "mongo-sth:27017"
#ENV CYGNUS_MONGO_USER ""
#ENV CYGNUS_MONGO_PASS ""
ENV CYGNUS_CKAN_HOST "<enter your ckan IP here>"
ENV CYGNUS_CKAN_PORT "<enter port here , if your ckan portal does not use port than leave it empty>"
ENV CYGNUS_CKAN_API_KEY "<put your ckan user api key here>"
#ENV CYGNUS_CKAN_SSL "false"
#ENV CYGNUS_HDFS_HOST "iot-hdfs"
#ENV CYGNUS_HDFS_PORT "50070"
#ENV CYGNUS_HDFS_USER "hdfs"
#ENV CYGNUS_HDFS_TOKEN ""
#ENV CYGNUS_CARTO_USER "carto"


#ENV CYGNUS_SERVICE_PORT "5050"
#ENV CYGNUS_API_PORT "8081"
COPY ./cygnus-entrypoint-custom.sh /cygnus-entrypoint.sh
RUN chmod +x /cygnus-entrypoint.sh

ENTRYPOINT ["/cygnus-entrypoint.sh"]

# Ports used by cygnus-ngsi
EXPOSE ${CYGNUS_SERVICE_PORT} ${CYGNUS_API_PORT}

