FROM rhcayadav/cygnus_custom-ckan_without_entrypoint:v1.1
MAINTAINER Francisco Romero Bueno <francisco.romerobueno@telefonica.com>


#ENV CYGNUS_SERVICE_PORT "5050"
#ENV CYGNUS_API_PORT "8081"
#ENV CYGNUS_MYSQL_HOST "iot-mysql"
#ENV CYGNUS_MYSQL_PORT "3306"
#ENV CYGNUS_MYSQL_USER "mysql"
#ENV CYGNUS_MYSQL_PASS "mysql"
ENV CYGNUS_MONGO_HOSTS "<sth-mongodb container IP>:<mongodb port generally 27017>"
ENV CYGNUS_MONGO_USER "<mongo user leave it empty if no user created ,  normally keep it empty>"
ENV CYGNUS_MONGO_PASS "<mongo password leave it empty if no user created, normally keep it empty>"
#ENV CYGNUS_CKAN_HOST ""
#ENV CYGNUS_CKAN_PORT ""
#ENV CYGNUS_CKAN_API_KEY ""
#ENV CYGNUS_CKAN_SSL "false"
#ENV CYGNUS_HDFS_HOST "iot-hdfs"
#ENV CYGNUS_HDFS_PORT "50070"
#ENV CYGNUS_HDFS_USER "hdfs"
#ENV CYGNUS_HDFS_TOKEN ""
#ENV CYGNUS_CARTO_USER "carto"
ENV CYGNUS_SERVICE_PORT "5050"
ENV CYGNUS_API_PORT "8081"
# SetUp wait script
#COPY ./wait-for-it.sh /wait-for-it.sh
# RUN chmod +x /wait-for-it.sh
#
# COPY ./agent_custom_comet.conf ${CYGNUS_CONF_FILE}
COPY ./cygnus-entrypoint-custom.sh /cygnus-entrypoint.sh
RUN chmod +x /cygnus-entrypoint.sh
#
# # Define the entry point
ENTRYPOINT ["/cygnus-entrypoint.sh"]
#
# # Ports used by cygnus-ngsi
EXPOSE ${CYGNUS_SERVICE_PORT} ${CYGNUS_API_PORT}
#
